### ISSUE TITLE
Fresh install error 

### ISSUE THREAD

**Issue by halfrubbish** [homespun/homebridge-accessory-neurio#4]
Seem to get the following error when it loads, despite pcap and pcap2 being installed. 

Any ideas?

`[28/09/2017, 23:01:28] ERROR LOADING PLUGIN homebridge-accessory-neurio:
[28/09/2017, 23:01:28] Error: Cannot find module './build/Release/pcap_binding'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-accessory-neurio/node_modules/pcap2/index.js:6:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
[28/09/2017, 23:01:28] ====================
/usr/local/lib/node_modules/homebridge/lib/api.js:64
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'neurio' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:254:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
`

**Comment by halfrubbish** [comment]
I fixed this, it was an install ordering issue. I npm uninstalled homebridge-accessory-neurio and then installed it again and all well! sorry for the noise!

**Comment by mrose17** [comment]
no worries! congrats on the fix!
